name: CI/CD Pipeline - Testing

on:
  push:
    branches:
      - main
      - develop
      - tests-cli
  pull_request:
    branches:
      - main
      - develop
      - tests-cli

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (using Python 3.8)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Upgrade pip, setuptools, and wheel
      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || exit 1

      # Step 5: Run tests
      - name: Run tests
        run: pytest
