name: CI/CD Pipeline - Testing

on:
  push:
    branches:
      - main
      - develop
      - tests-cli
  pull_request:
    branches:
      - main
      - develop
      - tests-cli

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip, setuptools, and wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
